# 日志配置文件

# 1. 更多日志级别
more_levels:

# 1.1 TRACE级别
# - 代替DEBUG级别
  _trace:
    name:  DEBUG
    level: 15

# 1.2. FATAL级别
# - 代替CRITICAL级别
  _fatal:
    name:  FATAL
    level: 55

# 1.3. 框架自定义日志级别
# - 最高日志级别，无论如何都要输出

# 1.3.1 TEST_CASE级别
# - 输出测试用例
  _case:
    name:  TEST_CASE
    level: 91

# 1.3.2 UNIT级别
# -  输出测试单元
  _unit:
    name:  TEST_UNIT
    level: 92

# 1.3.3 STEP级别
# - 输出测试步骤
  _step:
    name:  STEP
    level: 94

# 1.3.4 SUCCESS级别
# - 输出测试成功
  _pass:
    name:  PASS
    level: 96

# 1.3.5 FAIL级别
# - 输出测试失败
  _fail:
    name: FAIL
    level: 99

# 2. 基本配置
basic_config:
  format: '%(asctime)-16s | %(levelname)+10s | %(message)s'
  level:  10

